spring:
  application:
    name: auth-service
  profiles:
    active: local
springdoc:
  swagger-ui:
    path: /api/auth/swagger-ui
    config-url: /api/auth/v3/api-docs/swagger-config
    url: /api/auth/v3/api-docs