spring:
  kafka:
    bootstrap-servers: kafka.guideme.svc.cluster.local:9092
    consumer:
      group-id: guideme
    producer:
      bootstrap-servers: kafka.guideme.svc.cluster.local:9092

auth:
  oidc:
    issuer: https://idp.gistory.me
    authorize-uri: https://idp.gistory.me/authorize
    token-uri: https://api.idp.gistory.me/oauth/token
    client-id: ${OIDC_CLIENT_ID}
    client-secret: ${OIDC_CLIENT_SECRET}
    redirect-uri: https://api.guideme.my/api/auth/login/callback
    jwks-uri: https://api.idp.gistory.me/oauth/certs

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false


jwt:
  secret: ${JWT}
  issuer: ${ISSUER}

server:
  port: ${PORT:9000}
