eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-api
          uri: ${AUTH_SERVICE_PATH}
          predicates:
            - Path=/api/auth/**

        - id: auth-service-swagger-docs
          uri: ${AUTH_SERVICE_PATH}
          predicates:
            - Path=/v3/api-docs/auth/**
          filters:
            - RewritePath=/v3/api-docs/auth/(?<segment>.*), /v3/api-docs/${segment}

        - id: auth-service-swagger-ui
          uri: ${AUTH_SERVICE_PATH}
          predicates:
            - Path=/api/auth/swagger-ui/**

        - id: user-service-api
          uri: ${USER_SERVICE_PATH}
          predicates:
            - Path=/api/user/**

        - id: user-service-swagger-docs
          uri: ${USER_SERVICE_PATH}
          predicates:
            - Path=/v3/api-docs/user/**
          filters:
            - RewritePath=/v3/api-docs/user/(?<segment>.*), /v3/api-docs/${segment}

        - id: user-service-swagger-ui
          uri: ${USER_SERVICE_PATH}
          predicates:
            - Path=/api/user/swagger-ui/**
client:
  auth-service:
    url: ${AUTH_SERVICE_PATH}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true