spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
  profiles:
    active: local
#  config:
#    import:
#      - optional:classpath:application-prod.yaml
#      - optional:classpath:application-local.yaml
server:
  port: 8000
