spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
  config:
    import:
      - classpath:application-prod.yaml
      - classpath:application-local.yaml
      - optional:configserver:http://config-server:8888
  profiles:
    active: local
server:
  port: 8000
