spring:
  application:
    name: user-service
  profiles:
    active: local

  config:
    import:
      - optional:configserver:8888
      - classpath:application-prod.yaml
      - classpath:application-local.yaml

spring.cloud.config.fail-fast: true