spring:
  cloud:
    config:
      enabled: false
  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

firebase:
  bucket-name: ${BUCKET_NAME}
  url-format: https://firebasestorage.googleapis.com/v0/b/%s/o/%s?alt=media

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false

server:
  port: 9000

logging:
  level:
    root: INFO
    com.zaxxer.hikari: DEBUG
    com.zaxxer.hikari.pool: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN
