spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

firebase:
  bucket-name: ${BUCKET_NAME}
  url-format: https://firebasestorage.googleapis.com/v0/b/%s/o/%s?alt=media

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false

server:
  port: 9000
